import base64
import getpass
import os
import sys
from cryptography.fernet import Fernet, InvalidToken
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from typing import List, Tuple

# NOTE: encrypting/decryting a directory will attempt to use the same
# password for each file in the directory. If it doesn't work, it will
# move on to the next file.

""" Generates key given user password and salt.

Args:
    - password (bytes): User password in byte format.
    - salt (bytes): Randomly generated bytes for key generation.
Returns:
    - key (bytes): Encryption key in byte format.

"""
def gen_key(password: bytes, salt: bytes) -> bytes:
    # Key Derivation Function
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=480000,
    )
    key = base64.urlsafe_b64encode(kdf.derive(password))
    
    return key

""" Checks if the file is encrypted.

Args:
    - path (string): File path.

Returns:
    - (bool): If the file end with ".enc".
    - (List[str]): Split file path, with the last element being the file extension.
    - (bytes): The file extension encoded in utf-8.
"""
def check_encrypted(path: str) -> Tuple[bool, List[str], bytes]:
    split_path = path.split(".")
    file_extension = split_path[-1]

    # Check if file is already an .enc file
    is_encrypted = False
    if file_extension == "enc":
        is_encrypted = True
    
    # Convert file extension to byte format
    file_extension = file_extension.encode("utf-8")

    return is_encrypted, split_path, file_extension


""" Encrypt one file.

Args:
    - fernet_obj (Fernet): Object representing the encryption method.
    - path (string): File path.
    - salt (bytes): Randomly generated group of bytes.

Returns:
    - None

Helper function for encrypt_path().
"""
def encrypt_file(fernet_obj: Fernet, path: str, salt: bytes) -> None:
    # If file is already encrypted, end function early
    is_encrypted, split_path, file_extension = check_encrypted(path)
    if is_encrypted:
        print(f"{path} is already encoded, skipping this file.")
        return

    # Read file to be encrypted
    with open(path, "rb") as f:
        unencrypted_data = f.read()

    # Add file extension to the top of the unencrypted data
    unencrypted_data = file_extension + unencrypted_data
    # Encrypt data
    encrypted_data = fernet_obj.encrypt(unencrypted_data)
    # Change file extension to .enc
    new_path = split_path[0] + ".enc"

    # Write to file to be encrypted
    with open(new_path, "wb") as f:
        f.write(salt)
        f.write(encrypted_data)
    
    print(f"{path} encrypted.")


""" Encrypts selected file or directory.

Args:
    - path (str): File path.
    - password (bytes): User input password in byte format.

Returns:
    - None

If directory was passed in, only encrypt unencrypted files.
"""
def encrypt_path(path: str, password: bytes) -> None:
    # Generate salt for the key generation
    salt = os.urandom(16)
    # Pass password to determine key
    key = gen_key(password, salt)
    # Create Fernet object with key
    fernet_obj = Fernet(key)

    if os.path.isdir(path):
        for __, __, files in os.walk(path):
            for file in files:
                encrypt_file(fernet_obj, file, salt)
            break   # Avoid recursing into subdirectories
        pass
    else:
        encrypt_file(fernet_obj, path, salt)


""" Decrypts one file.

Args:
    - fernet_obj (Fernet): Object representing the encryption method.
    - path (string): File path.

Returns:
    - None

Helper function for decrypt_path().
"""
def decrypt_file(fernet_obj: Fernet, path: str) -> None:
    # TODO: make sure you separate the original file extension from data
    # TODO: if password doesn't work for file, skip
    # Check if it's an encrypted file
    #TODO i'm sorry 4/1
    is_encrypted, split_path, file_extension = check_encrypted(path)
    
    # Read encrypted data
    with open(path, "rb") as f:
        encrypted_data = f.read()

    # Derive key using the salt in file (first 16 bytes)
    salt = encrypted_data[:16]
    # Actual data with original file extension on top
    encrypted_data = encrypted_data[16:]

    try:
        # Decrypt
        decrypted_data = fernet_obj.decrypt(encrypted_data)
    except InvalidToken:
        print("Error: Incorrect password or corrupted file.")
        sys.exit(1)
    pass


""" Decrypts selected file or directory.

Args:
    - path (str): File path.
    - password (bytes): User input password in byte format.

Returns:
    - None

If directory was passed in, only decrypt encrypted files.
"""
def decrypt_path(path: str, password: bytes) -> None:
    pass

# TODO: add functionality to encrypt/decrypt all files in a directory
# Make sure to ask for another confirmation from user

# TODO: change file extension to .enc and save original extension to file
# before encryption.

def main():
    # Ask user if they want to encrypt or decrypt
    while True:
        encrypt_or_decrypt = input("Encrypt or decrypt? [e/d] ")
        if encrypt_or_decrypt not in ["d", "e"]:
            print("Invalid input.")
        else:
            while True:
                # Obtain file/directory path
                user_path = input(
                    f"Enter path of file or directory to "
                    f"{'encrypt' if encrypt_or_decrypt == 'e' else 'decrypt'}: "
                )
                # Check if user chose an entire directory and ask to confirm
                is_dir = os.path.isdir(user_path)
                if is_dir:
                    while True:
                        confirm_encrypt_dir = input("Are you sure you want to perform this action \
                                                    on the entire directory? [y/n] ")
                        if confirm_encrypt_dir in ["n", "y"]:
                            # Received valid input from user
                            break
                        else:
                            print("Invalid input.")

                    if confirm_encrypt_dir == "y":
                        # Continue with process
                        break
                    else:
                        # Ask user for path again
                        continue
                else:
                    # Continue with process
                    break
            break

    # Check if file is already encrypted. If user wants to encrypt,
    # end the program early
    if not is_dir:
        is_encrypted, __, __ = check_encrypted(user_path)
        if is_encrypted and encrypt_or_decrypt == "e":
            print(f"{user_path} is already encoded.")
            return

    # TODO: maybe consider doing this in the encrypt_path and decrypt_path funcs
    # User enters the password for the file
    password = getpass.getpass("Enter password: ")
    # Save password in a byte format
    password = password.encode("utf-8")

    # Choose between encryption or decryption
    if encrypt_or_decrypt == "e":
        encrypt_path(user_path, password)
    elif encrypt_or_decrypt == "d":
        decrypt_path(user_path, password)
    else:
        # You should never be here
        sys.exit("Error: Invalid action.")
    
    print("Complete.")
    

if __name__ == '__main__':
    main()